title: ZeHua Wu | Portfolio
url: "https://hmxsqaq.github.io"
baseurl: ""

techfolio-theme: rubik.css
rouge-theme: github.css

markdown: kramdown
kramdown:
  hard_wrap: false
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    line_numbers: false
strict_front_matter: true
mathjax: true
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
include:
  - .nojekyll
  - _data
plugins:
  - jekyll-gist
